#!/bin/dash
#MOUHAMADOU LAMINE MBOUP & KADIR GUZEL 


#EXERCISE 2
#QUESTION 2.1
#FONCTION USAGE
usage(){
	echo "Usage: generateMakefile.sh name [directory]"
	echo "where:"
	echo "\tname is the name of the program"
	echo "\tdirectory is the source directory"
}
#QUESTION 2.2
#TESTING ARGUMENTS 
if test "$#" -ne 1 && test "$#" -ne 2
then
	echo "Number of arguments incorrect." >&2
	usage >&2
	exit 1
fi

if test "$#" -eq 2
then
	if test ! -d "$2"
	then
		echo "$2 isn't a directory or doesn't exist."
		usage >&2
		exit 2
	fi
	cd "$2"
fi

ROOTDIR=$(pwd)

#EXERCISE 3
#GET ALL DEPENDANCE OF THE .c FILE
get_dependance(){
	DEPS=$(grep -E '#include' "$1" | grep -Ev '<'| sed -r 's/(#include|"| )//g' | tr '\n' ' ')
	
	if test ! "$DEPS" = "" 
	then
		cd $ROOTDIR
		DEPSS=$(find . -name $DEPS)
		cd $2
		echo $DEPSS
		get_dependance $DEPS $2
	fi	
}

IFSMEM=IFS
IFS=" "
#EXERCISE 5
#QUESTION 5.1
#TEST IF THERE IS .c IN CURRENT DIRECTORY
FICHIERC=$(ls | grep .c | wc -l)
if test $FICHIERC -eq 0
then
	echo "There isn't .c file in current directory">&2
	usage >&2
	exit 3
fi

FICHIERC=$(ls | grep .c)
#GET EVERY .o FILE IN EVERY DIRECTORY
OFILES(){
	echo $(ls | grep .c | tr '.c' '.o' | tr '\n' ' ')
	for I in * 
	do
		if test -d $I 
		then
			cd $I
			OFILES
			cd ..
		fi
	done
}

FICHIERO=$(OFILES | tr '\n' ' ')
#QUESTION 5.2
echo "#Generated by generateMakefile.sh">Makefile
echo "CC=gcc">>Makefile
echo "CFLAGS=$CFLAGS">>Makefile
echo "LDFLAGS=$LDFLAGS">>Makefile
#QUESTION 5.3
echo "all: $1\n">>Makefile
echo "$1: $FICHIERO">>Makefile
echo "\t\$(CC) \$(LDFLAGS) $FICHIERO -o $1">>Makefile
ROOTDIR=$(pwd)
#WRITE EVERY DEPENDANCE INTO THE MAKEFILE
write_dependance(){
	DIR=$1
	#QUESTION 5.4
	#GO THROUGH EVERY .c FILE AND CREATE THE MAKEFILE
	for I in *.c 
	do
		FICHIERO=$(echo $I | tr '.c' '.o')
		cd $ROOTDIR
		J=$(find . -name $I)
		cd $DIR
		echo -n "$FICHIERO : $J "
		ALLDEPS=$(get_dependance $I $1 | tr ' ' '\n' | uniq | tr '\n' ' ')
		echo $ALLDEPS
		# cd $ROOTDIR
		# echo $(find . -name $ALLDEPS)
		# cd $DIR
		echo "\t\$(CC) \$(CFLAGS) -c -o $FICHIERO $I"
	done
}
#BROWSE EVERY DIRECTORY
bonus(){
	DIR=$(pwd)
	write_dependance $DIR
	for I in * 
	do
		if test -d $I 
		then
			cd $I
			bonus
			cd ..
		fi
	done
}
#WRTIE INTO MAKEFILE 
bonus>>Makefile

cd $ROOTDIR
#QUESTION 5.7
echo "\nclean:\n\trm -f *.o\nmrproper: clean\n\trm -f $1">>Makefile
IFS=IFSMEM


