#!/bin/dash
#MOUHAMADOU LAMINE MBOUP & KADIR GUZEL 


#EXERCISE 2
#QUESTION 2.1
#FONCTION USAGE 
usage(){
	echo "Usage: generateMakefile.sh name [directory]"
	echo "where:"
	echo "\tname is the name of the program"
	echo "\tdirectory is the source directory"
}
#QUESTION 2.2
#TESTING ARGUMENTS 
if test "$#" -ne 1 && test "$#" -ne 2
then
	echo "Number of arguments incorrect." >&2
	usage >&2
	exit 1
fi
if test "$#" -eq 2
then
	if test ! -d "$2"
	then
		echo "$2 isn't a directory or doesn't exist."
		usage >&2
		exit 2
	fi
	cd "$2"
fi

ROOTDIR=$(pwd)

#EXERCISE 3
#GET ALL DEPENDANCE OF THE .c FILE
get_dependance(){
	DEPS=$(grep -E '#include' "$1" | grep -Ev '<'| sed -r 's/(#include|"| )//g' | tr '\n' ' ')
	echo "$DEPS"
	if test ! "$DEPS" = "" 
	then
		get_dependance $DEPS 
	fi	
}

IFSMEM=IFS
IFS=" "

#EXERCISE 5
#QUESTION 5.1
#TEST IF THERE IS .c IN CURRENT DIRECTORY
FICHIERC=$(ls | grep .c | wc -l)
if test $FICHIERC -eq 0
then
	echo "There isn't .c file in current directory">&2
	usage >&2
	exit 3
fi


FICHIERO=$(ls | grep .c | tr '.c' '.o' | tr '\n' ' ')
#QUESTION 5.2
echo "#Generated by generateMakefile.sh">Makefile
echo "CC=gcc">>Makefile
echo "CFLAGS=$CFLAGS">>Makefile
echo "LDFLAGS=$LDFLAGS">>Makefile
#QUESTION 5.3
echo "all: $1\n">>Makefile
echo "$1: $FICHIERO">>Makefile
echo "\t\$(CC) \$(LDFLAGS) $FICHIERO -o $1">>Makefile

#QUESTION 5.4
#GO THROUGH EVERY .c FILE AND CREATE THE MAKEFILE 
for I in *.c 
do
	FICHIERO=$(echo $I | tr '.c' '.o')
	echo -n "$FICHIERO : $I ">>Makefile
	echo $(get_dependance $I | tr ' ' '\n' | uniq | tr '\n' ' ')>>Makefile
	echo "\t\$(CC) \$(CFLAGS) -c -o $FICHIERO $I">>Makefile
done

#QUESTION 5.7
echo "\nclean:\n\trm -f *.o\nmrproper: clean\n\trm -f $1">>Makefile
IFS=IFSMEM


